<a href="https://colab.research.google.com/github/adindasyv/2141720096-machinelearning-2023/blob/master/Week%209/tugas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TUGAS PRAKTIKUM
1. Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
2. Anda diperbolehkan melakukan eksplorasi terhadap,
- Metode pra pengolahan
- Pemilihan fitur
- Arsitektur ANN
- Fungsi Aktiviasi
3. ANN diimplementasikan dengan menggunakan tensowflow
4. DIKERJAKAN SECARA BERKELOMPOK
5. JELASKAN HASIL YANG ANDA DAPATKAN.
- AKURASI
- CONFUSION MATRIX
- KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

### Langkah 1 - Impor Library


In [2]:
import tensorflow as tf
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix, accuracy_score

In [3]:
data_mnist = datasets.fetch_openml("mnist_784")

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


### Langkah 2 - Eksplorasi Dataset

In [7]:
# Melihat dimensi data
print("Jumlah sampel MNIST:", data_mnist.data.shape[0])  # Jumlah sampel
print("Dimensi setiap sampel MNIST:", data_mnist.data.shape[1])  # Dimensi setiap sampel
print("Jumlah kelas MNIST:", len(set(data_mnist.target)))  # Jumlah kelas

Jumlah sampel MNIST: 70000
Dimensi setiap sampel MNIST: 784
Jumlah kelas MNIST: 10


In [8]:
# mengambil data dan label
X = data_mnist.data.astype('float32')
y = data_mnist.target.astype('int')

In [9]:
X.shape

(70000, 784)

In [14]:
# scaling data menggunakan MinMaxScaler
scaler = MinMaxScaler()
X_scalling = scaler.fit_transform(X)

In [15]:
print(X_scalling[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### Langkah 3 - Ekstraksi Fitur dan Split Data

In [16]:
pca = PCA(n_components=200)
X_pca = pca.fit_transform(X_scalling)

In [17]:
# Split dataset menjadi data pelatihan dan data pengujian
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size = 0.2, random_state = 42)

### Langkah 4 - Membangun Model ANN

In [19]:
# Membuat model ANN
model = Sequential()

# Tambahkan lapisan input
model.add(Dense(units=128, activation='relu', input_dim=200))  # 128 unit pada lapisan tersembunyi pertama

# Tambahkan lapisan tersembunyi pertama
model.add(Dense(units=64, activation='relu'))  # 64 unit pada lapisan tersembunyi kedua

# Tambahkan lapisan tersembunyi kedua
model.add(Dense(units=32, activation='relu'))  # 32 unit pada lapisan tersembunyi ketiga

# Tambahkan lapisan output
model.add(Dense(units=10, activation='softmax'))  # 10 unit pada lapisan output untuk klasifikasi 10 kelas

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 128)               25728     
                                                                 
 dense_5 (Dense)             (None, 64)                8256      
                                                                 
 dense_6 (Dense)             (None, 32)                2080      
                                                                 
 dense_7 (Dense)             (None, 10)                330       
                                                                 
Total params: 36394 (142.16 KB)
Trainable params: 36394 (142.16 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### Langkah 5 - Training Model

In [20]:
# Kompilasi model ANN
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [21]:
# Melatih model menggunakan data pelatihan
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)  # Contoh menggunakan 10 epoch dan ukuran batch 32

# Evaluasi model menggunakan data pengujian
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss:", loss)
print("Accuracy:", accuracy)

Epoch 1/10
1400/1400 [==============================] - 5s 3ms/step - loss: 0.2967 - accuracy: 0.9121 - val_loss: 0.1435 - val_accuracy: 0.9560
Epoch 2/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.1006 - accuracy: 0.9695 - val_loss: 0.1155 - val_accuracy: 0.9640
Epoch 3/10
1400/1400 [==============================] - 7s 5ms/step - loss: 0.0642 - accuracy: 0.9803 - val_loss: 0.1073 - val_accuracy: 0.9663
Epoch 4/10
1400/1400 [==============================] - 7s 5ms/step - loss: 0.0428 - accuracy: 0.9865 - val_loss: 0.1071 - val_accuracy: 0.9678
Epoch 5/10
1400/1400 [==============================] - 4s 3ms/step - loss: 0.0312 - accuracy: 0.9898 - val_loss: 0.1043 - val_accuracy: 0.9705
Epoch 6/10
1400/1400 [==============================] - 5s 3ms/step - loss: 0.0243 - accuracy: 0.9918 - val_loss: 0.1169 - val_accuracy: 0.9693
Epoch 7/10
1400/1400 [==============================] - 6s 4ms/step - loss: 0.0189 - accuracy: 0.9938 - val_loss: 0.1288 - val_accuracy:

### Langkah 6 - Evaluasi

In [22]:
# Evaluasi model pada data pelatihan
train_loss, train_accuracy = model.evaluate(X_train, y_train)
print("Train Loss:", train_loss)
print("Train Accuracy:", train_accuracy)

1750/1750 [==============================] - 6s 3ms/step - loss: 0.0382 - accuracy: 0.9907
Train Loss: 0.03817214444279671
Train Accuracy: 0.9906785488128662


In [23]:
# Evaluasi model pada data pengujian
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

438/438 [==============================] - 3s 7ms/step - loss: 0.1640 - accuracy: 0.9672
Test Loss: 0.16401049494743347
Test Accuracy: 0.9672142863273621


In [25]:
# Melakukan prediksi menggunakan model pada data pengujian
predictions = model.predict(X_test)

# Mengubah prediksi dari format one-hot encoded ke kelas
predicted_classes = np.argmax(predictions, axis=1)

# Menghitung confusion matrix
confusion_mtx = confusion_matrix(y_test, predicted_classes)

print("Confusion Matrix:")
print(confusion_mtx)

438/438 [==============================] - 2s 4ms/step
Confusion Matrix:
[[1319    0    6    0    2    0    6    1    5    4]
 [   0 1570    6    7    0    0    5    3    8    1]
 [   2    2 1329    8    5    5    6    6   15    2]
 [   1    0   18 1377    0   18    2    2   13    2]
 [   3    0    3    0 1261    1    3    6    2   16]
 [   3    1    0   10    0 1236    9    1   11    2]
 [   5    0    5    0    6    6 1371    0    3    0]
 [   4    6   19    8    8    3    0 1439    5   11]
 [   4    3    9   15    3   12    6    5 1297    3]
 [   8    1    2    6   27    8    0   17    9 1342]]
